export interface eventConfigFormInitialValueType {
  sqldate: [number, number] | null,
  // dataSource: string,
  weightBasis: number,
  statisticsBasis: number,
  actor1countrycode: Array<string> | null,
  actor1knowngroupcode: Array<string> | null,
  actor1religion1code: Array<string> | null,
  actor1religion2code: Array<string> | null,
  actor1ethniccode: Array<string> | null,
  actor1type1code: Array<string> | null,
  actor1type2code: Array<string> | null,
  actor1type3code: Array<string> | null,
  actor1name: string | null,
  actor1nameIsBig: number,
  actor1geoType: Array<string> | null,
  actor1geoCountrycodeAndAdm1code: Array<string> | null,
  actor1geoFullname: string | null,
  actor1geoFullnameIsBig: number,
  actor2countrycode: Array<string> | null,
  actor2knowngroupcode: Array<string> | null,
  actor2religion1code: Array<string> | null,
  actor2religion2code: Array<string> | null,
  actor2ethniccode: Array<string> | null,
  actor2type1code: Array<string> | null,
  actor2type2code: Array<string> | null,
  actor2type3code: Array<string> | null,
  actor2name: string | null,
  actor2nameIsBig: number,
  actor2geoType: Array<string> | null,
  actor2geoCountrycodeAndAdm1code: Array<string> | null,
  actor2geoFullname: string | null,
  actor2geoFullnameIsBig: number,
  quadclass: Array<string> | null,
  eventrootcode: Array<string> | null,
  eventbasecode: Array<string> | null,
  eventcode: Array<string> | null,
  actiongeoType: Array<string> | null,
  actiongeoCountrycodeAndAdm1code: Array<string> | null,
  actiongeoFullname: string | null,
  actiongeoFullnameIsBig: number,
  sourceUrl: string | null,
  beginAvgtone: number | null,
  endAvgtone: number | null,
  // avgtone: Array<number | null>,
  beginGoldsteinscale: number | null,
  endGoldsteinscale: number | null,
  // goldsteinscale: Array<number | null>,
  isrootevent: number | null,
  numsourcesMin: number | null,
  numsourcesMax: number | null,
  nummentionsMin: number | null,
  nummentionsMax: number | null,
  numarticlesMin: number | null,
  numarticlesMax: number | null,
}