export interface graphConfigFormInitialValueType {
  sqldate: [number, number] | null,
  weightBasis: number,
  statisticsBasis: number,
  counts: string,
  countsIsBig: number,
  themes: string,
  themesIsBig: number,
  locations: string,
  locationsIsBig: number,
  persons: string,
  personsIsBig: number,
  organizations: string,
  organizationsIsBig: number,
  websiteRegion: Array<string> | null,
  websiteUrl: string,
  cameoeventids: string,
  cameoeventidsIsAnd: number,
  avgEmMin: number | null,
  avgEmMax: number | null,
  proEmMin: number | null,
  proEmMax: number | null,
  negEmMin: number | null,
  negEmMax: number | null,
  polRaMin: number | null,
  polRaMax: number | null,
  actRaMin: number | null,
  actRaMax: number | null,
  propRaMin: number | null,
  propRaMax: number | null
}